Repository CSE-112-Team-7/Stargazer-V2, pull requests merged in 2024-06, with the labels that each got.

#21 13 store user history
  admin/database/er_diagarm.drawio
  admin/database/er_diagarm.png
  backend/index.mjs
  backend/package-lock.json
  backend/package.json
  backend/routes.mjs
  source/assets/teller/start-image.png
  source/pages/explanation_page/explanation.css
  source/pages/explanation_page/explanation.html
  source/pages/explanation_page/explanation.js
  source/pages/login_index_page/login_index.css
  source/pages/login_index_page/login_index.html
  source/pages/login_index_page/login_index.js
  source/pages/login_page/login.css
  source/pages/login_page/login.html
  source/pages/login_page/login.js
  source/pages/response_page/response.html
  source/pages/response_page/response.js
  source/pages/selection_page/selection.css
  source/pages/selection_page/selection.html
  source/pages/selection_page/selection.js
  source/pages/signup_page/signup.css
  source/pages/signup_page/signup.html
  source/pages/signup_page/signup.js
  source/pages/skymap_page/Background.js
  source/pages/skymap_page/Constellation.js
  source/pages/skymap_page/skymap.html
  source/pages/skymap_page/skymap.js
  source/pages/starting_page/starting.html
  source/pages/thankyou_page/thankyou.html
  source/pages/thankyou_page/thankyou.js
  source/pages/toplevel.css
Labels: enhancement, UI

#28 23 fix original tests to match with backend
  .github/workflows/tests.yml
  backend/index.mjs
  package-lock.json
  package.json
  source/pages/explanation_page/explanation.html
  source/pages/selection_page/selection.css
  source/pages/selection_page/selection.html
  source/pages/selection_page/selection.js
  source/tests/defaultpuppeteer.test.js
  source/tests/explanation.test.js
  source/tests/fullend2end.test.js
  source/tests/landing.test.js
  source/tests/landingpuppeteer.test.js
  source/tests/response.test.js
  source/tests/responsepuppeteer.test.js
  source/tests/selection.test.js
  source/tests/skymap.test.js
  source/tests/starting.test.js
  source/tests/thankyou.test.js
  source/tests/thankyoupuppeteer.test.js
  sum.js
  sum.test.js
Labels: CI/CD, tests

#30 29 reformat any files failing tests with prettier
  admin/workplan-200524.md
  admin/workplan.md
  backend/index.mjs
  backend/routes.mjs
  source/pages/explanation_page/explanation.html
  source/pages/explanation_page/explanation.js
  source/pages/login_index_page/login_index.html
  source/pages/login_page/login.html
  source/pages/response_page/response.html
  source/pages/response_page/response.js
  source/pages/selection_page/selection.html
  source/pages/signup_page/signup.html
  source/pages/skymap_page/Background.js
  source/pages/skymap_page/BackgroundStar.js
  source/pages/skymap_page/Constellation.js
  source/pages/skymap_page/ConstellationStar.js
  source/pages/skymap_page/skymap.html
  source/pages/skymap_page/skymap.js
  source/pages/starting_page/starting.html
  source/pages/thankyou_page/thankyou.html
  source/pages/thankyou_page/thankyou.js
  source/tests/fullend2end.test.js
  source/tests/response.test.js
  source/tests/selection.test.js
  source/tests/skymap.test.js
  source/tests/starting.test.js
  source/utils/playClickSound.js
  sum.js
  sum.test.js
Labels: CI/CD

#36 places horoscope into db in response page
  backend/index.mjs
  source/pages/response_page/response.js
  source/pages/thankyou_page/thankyou.html
  source/tests/fullend2end.test.js
Labels: enhancement

#40 History page
  backend/index.mjs
  backend/routes.mjs
  source/pages/explanation_page/explanation.html
  source/pages/history_page/history.css
  source/pages/history_page/history.html
  source/pages/history_page/history.js
  source/pages/login_index_page/login_index.css
  source/pages/login_index_page/login_index.html
  source/pages/login_index_page/login_index.js
  source/pages/login_page/login.html
  source/pages/login_page/login.js
  source/pages/response_page/response.html
  source/pages/selection_page/selection.css
  source/pages/selection_page/selection.html
  source/pages/signup_page/signup.html
  source/pages/starting_page/starting.css
  source/pages/starting_page/starting.html
  source/pages/starting_page/starting.js
  source/pages/thankyou_page/thankyou.html
  source/utils/setting.js
Labels: enhancement, UI

#41 update login and signup style
  source/pages/login_page/login.css
  source/pages/login_page/login.html
  source/pages/login_page/login.js
  source/pages/signup_page/signup.css
  source/pages/signup_page/signup.html
  source/pages/signup_page/signup.js
Labels: UI

#43 42 write new tests for login signup pages
  source/tests/login.test.js
  source/tests/signup.test.js
Labels: CI/CD, tests

#45 revert to original docs yml file
  .github/workflows/documentation.yml
Labels: bug, CI/CD
